using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace backend.Models;

/// <summary>
/// This model matches the database-level audit logs generated by PostgreSQL triggers.
/// It uses JSONB for OldData and NewData to capture full record snapshots.
/// </summary>
public class AuditLog
{
    [Key]
    public int AuditId { get; set; }

    public string? TableName { get; set; }
    public string? RecordId { get; set; }
    public string? Action { get; set; } // INSERT, UPDATE, DELETE

    [Column(TypeName = "jsonb")]
    public string? OldData { get; set; }

    [Column(TypeName = "jsonb")]
    public string? NewData { get; set; }

    public string? ChangedBy { get; set; }

    public DateTime ChangedAt { get; set; } = DateTime.UtcNow;
}
