CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AccomplishmentReports" (
    "ReportId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text,
    "ReceiverId" text,
    "ViewerId" text,
    "Date" date NOT NULL,
    "Title" character varying(50),
    "Tasks" jsonb NOT NULL,
    "FeedbackHistory" jsonb NOT NULL,
    "Status" text,
    "ReturnedById" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AccomplishmentReports" PRIMARY KEY ("ReportId")
);

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FullName" text,
    "Position" text,
    "Department" text,
    "EmployeeID" integer,
    "SupervisorId" text,
    "ViewerId" text,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "DeactivatedAccounts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "FullName" text NOT NULL,
    "Email" text NOT NULL,
    "Position" text,
    "Department" text,
    "Role" text,
    "DeactivatedByUserId" text NOT NULL,
    "DeactivatedByUserName" text NOT NULL,
    "DeactivatedAt" timestamp with time zone NOT NULL,
    "Reason" text,
    CONSTRAINT "PK_DeactivatedAccounts" PRIMARY KEY ("Id")
);

CREATE TABLE "DeletedAccomplishmentReports" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OriginalReportId" integer NOT NULL,
    "UserId" text NOT NULL,
    "Title" text,
    "Date" date NOT NULL,
    "Status" text NOT NULL,
    "Tasks" jsonb NOT NULL,
    "FeedbackHistory" jsonb NOT NULL,
    "DeletedByUserId" text NOT NULL,
    "DeletedByUserName" text NOT NULL,
    "DeletedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DeletedAccomplishmentReports" PRIMARY KEY ("Id")
);

CREATE TABLE "DeletedAccounts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OriginalUserId" text NOT NULL,
    "FullName" text NOT NULL,
    "Email" text NOT NULL,
    "Position" text,
    "Department" text,
    "EmployeeID" integer,
    "Role" text,
    "Claims" text,
    "DeletedByUserId" text NOT NULL,
    "DeletedByUserName" text NOT NULL,
    "DeletedAt" timestamp with time zone NOT NULL,
    "Reason" text,
    CONSTRAINT "PK_DeletedAccounts" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RefreshTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Token" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiryDate" timestamp with time zone NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260427013517_InitialCreate', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "AccomplishmentReports" ADD "ViewedAt" timestamp with time zone;

ALTER TABLE "AccomplishmentReports" ADD "ViewedById" text;

ALTER TABLE "AccomplishmentReports" ADD "ViewedByName" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260427034233_AddViewedTracking', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Title" text NOT NULL,
    "Body" text NOT NULL,
    "LinkTo" text,
    "EventType" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260427041129_AddNotificationsTable', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "AccomplishmentReports" DROP CONSTRAINT "PK_AccomplishmentReports";

ALTER TABLE "AccomplishmentReports" RENAME TO "AccomplishmentReportEXP";

ALTER TABLE "AccomplishmentReportEXP" ADD CONSTRAINT "PK_AccomplishmentReportEXP" PRIMARY KEY ("ReportId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260429052244_FixTableMapping', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "AccomplishmentReportEXP" ADD "ApprovedById" text;

ALTER TABLE "AccomplishmentReportEXP" ADD "ApprovedByName" text;

ALTER TABLE "AccomplishmentReportEXP" ADD "ReturnedByName" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260429061004_AddApprovedAndReturnedNamesV2', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Notifications" ADD "ReportId" integer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260429074713_AddReportIdToNotification', '10.0.5');

COMMIT;

START TRANSACTION;
DROP TABLE "DeactivatedAccounts";

DROP TABLE "DeletedAccomplishmentReports";

DROP TABLE "DeletedAccounts";

ALTER TABLE "AspNetUsers" ADD "IsActive" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "AspNetUsers" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "AccomplishmentReportEXP" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260430053250_SoftDeleteRefactor', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "AccomplishmentReportEXP" ALTER COLUMN "Title" TYPE character varying(64);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260430063712_UpdateModelToLatest', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TABLE "AuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Action" text,
    "AdminId" text,
    "AdminName" text,
    "TargetUserId" text,
    "TargetUserName" text,
    "Details" text,
    "Timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260430074847_AddAuditLogs', '10.0.5');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260430103451_ResolveMergeConflict', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "AccomplishmentReportEXP" ADD "IdempotencyKey" uuid;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260430130041_AddIdempotencyKeyToAccomplishmentReport', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE UNIQUE INDEX "IX_AccomplishmentReportEXP_IdempotencyKey" ON "AccomplishmentReportEXP" ("IdempotencyKey");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260430131029_AddUniqueIdempotencyKeyIndex', '10.0.5');

COMMIT;

START TRANSACTION;

                INSERT INTO "AspNetUserRoles" ("UserId", "RoleId")
                SELECT ur."UserId", (SELECT "Id" FROM "AspNetRoles" WHERE "Name" = 'SuperAdmin' LIMIT 1)
                FROM "AspNetUserRoles" ur
                JOIN "AspNetRoles" r ON ur."RoleId" = r."Id"
                WHERE r."Name" = 'HR Management'
                AND ur."UserId" NOT IN (
                    SELECT "UserId" FROM "AspNetUserRoles"
                    WHERE "RoleId" = (SELECT "Id" FROM "AspNetRoles" WHERE "Name" = 'SuperAdmin' LIMIT 1)
                );
            


                DELETE FROM "AspNetUserRoles"
                WHERE "RoleId" = (SELECT "Id" FROM "AspNetRoles" WHERE "Name" = 'HR Management' LIMIT 1);
            


                DELETE FROM "AspNetRoles" WHERE "Name" = 'HR Management';
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260430155744_UnifyAdminRoles', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "AuditLogs" DROP COLUMN "AdminId";

ALTER TABLE "AuditLogs" DROP COLUMN "AdminName";

ALTER TABLE "AuditLogs" DROP COLUMN "Details";

ALTER TABLE "AuditLogs" DROP COLUMN "TargetUserId";

ALTER TABLE "AuditLogs" RENAME COLUMN "Timestamp" TO "ChangedAt";

ALTER TABLE "AuditLogs" RENAME COLUMN "TargetUserName" TO "ChangedBy";

ALTER TABLE "AuditLogs" RENAME COLUMN "Id" TO "AuditId";

ALTER TABLE "AuditLogs" ALTER COLUMN "Action" DROP NOT NULL;

ALTER TABLE "AuditLogs" ADD "NewData" jsonb;

ALTER TABLE "AuditLogs" ADD "OldData" jsonb;

ALTER TABLE "AuditLogs" ADD "RecordId" text;

ALTER TABLE "AuditLogs" ADD "TableName" text;


                ALTER TABLE "AuditLogs" ALTER COLUMN "ChangedAt" SET DEFAULT now();
                ALTER TABLE "AuditLogs" ALTER COLUMN "TableName" DROP NOT NULL;
                ALTER TABLE "AuditLogs" ALTER COLUMN "RecordId" DROP NOT NULL;
                ALTER TABLE "AuditLogs" ALTER COLUMN "Action" DROP NOT NULL;
            


                CREATE OR REPLACE FUNCTION audit_trigger_func()
                RETURNS TRIGGER AS $$
                DECLARE
                    current_user_id TEXT;
                BEGIN
                    current_user_id := current_setting('app.current_user_id', true);
                    
                    IF (TG_OP = 'INSERT') THEN
                        INSERT INTO "AuditLogs" ("TableName", "RecordId", "Action", "NewData", "ChangedBy", "ChangedAt")
                        VALUES (TG_TABLE_NAME, CAST(NEW."ReportId" AS TEXT), 'INSERT', to_jsonb(NEW), current_user_id, now());
                        RETURN NEW;
                    ELSIF (TG_OP = 'UPDATE') THEN
                        INSERT INTO "AuditLogs" ("TableName", "RecordId", "Action", "OldData", "NewData", "ChangedBy", "ChangedAt")
                        VALUES (TG_TABLE_NAME, CAST(NEW."ReportId" AS TEXT), 'UPDATE', to_jsonb(OLD), to_jsonb(NEW), current_user_id, now());
                        RETURN NEW;
                    ELSIF (TG_OP = 'DELETE') THEN
                        INSERT INTO "AuditLogs" ("TableName", "RecordId", "Action", "OldData", "ChangedBy", "ChangedAt")
                        VALUES (TG_TABLE_NAME, CAST(OLD."ReportId" AS TEXT), 'DELETE', to_jsonb(OLD), current_user_id, now());
                        RETURN OLD;
                    END IF;
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;
            


                CREATE OR REPLACE FUNCTION audit_users_trigger_func()
                RETURNS TRIGGER AS $$
                DECLARE
                    current_user_id TEXT;
                BEGIN
                    current_user_id := current_setting('app.current_user_id', true);
                    
                    IF (TG_OP = 'INSERT') THEN
                        INSERT INTO "AuditLogs" ("TableName", "RecordId", "Action", "NewData", "ChangedBy", "ChangedAt")
                        VALUES (TG_TABLE_NAME, NEW."Id", 'INSERT', to_jsonb(NEW), current_user_id, now());
                        RETURN NEW;
                    ELSIF (TG_OP = 'UPDATE') THEN
                        INSERT INTO "AuditLogs" ("TableName", "RecordId", "Action", "OldData", "NewData", "ChangedBy", "ChangedAt")
                        VALUES (TG_TABLE_NAME, NEW."Id", 'UPDATE', to_jsonb(OLD), to_jsonb(NEW), current_user_id, now());
                        RETURN NEW;
                    ELSIF (TG_OP = 'DELETE') THEN
                        INSERT INTO "AuditLogs" ("TableName", "RecordId", "Action", "OldData", "ChangedBy", "ChangedAt")
                        VALUES (TG_TABLE_NAME, OLD."Id", 'DELETE', to_jsonb(OLD), current_user_id, now());
                        RETURN OLD;
                    END IF;
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;
            


                DROP TRIGGER IF EXISTS audit_ar_trigger ON "AccomplishmentReportEXP";
                CREATE TRIGGER audit_ar_trigger
                AFTER INSERT OR UPDATE OR DELETE ON "AccomplishmentReportEXP"
                FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();
            


                DROP TRIGGER IF EXISTS audit_users_trigger ON "AspNetUsers";
                CREATE TRIGGER audit_users_trigger
                AFTER INSERT OR UPDATE OR DELETE ON "AspNetUsers"
                FOR EACH ROW EXECUTE FUNCTION audit_users_trigger_func();
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260501084423_UpdateAuditLogsToTriggers', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "AuditLogs" ALTER COLUMN "TableName" DROP NOT NULL;

ALTER TABLE "AuditLogs" ALTER COLUMN "RecordId" DROP NOT NULL;

ALTER TABLE "AuditLogs" ALTER COLUMN "Action" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260501094019_SyncAuditLogNullableFields', '10.0.5');

COMMIT;

START TRANSACTION;

-- 1. Refined Audit Function for Reports
CREATE OR REPLACE FUNCTION audit_trigger_func()
RETURNS TRIGGER AS $$
DECLARE
    current_user_id TEXT;
BEGIN
    BEGIN
        current_user_id := current_setting('app.current_user_id', true);
    EXCEPTION WHEN OTHERS THEN
        current_user_id := 'SYSTEM';
    END;
    
    IF current_user_id IS NULL OR current_user_id = '' THEN 
        current_user_id := 'SYSTEM'; 
    END IF;

    IF (TG_OP = 'INSERT') THEN
        INSERT INTO "AuditLogs" ("TableName", "RecordId", "Action", "NewData", "ChangedBy", "ChangedAt")
        VALUES (TG_TABLE_NAME, CAST(NEW."ReportId" AS TEXT), 'INSERT', to_jsonb(NEW), current_user_id, now());
    ELSIF (TG_OP = 'UPDATE') THEN
        -- Optimization: Only log if data actually changed
        IF (to_jsonb(OLD) = to_jsonb(NEW)) THEN RETURN NEW; END IF;
        
        INSERT INTO "AuditLogs" ("TableName", "RecordId", "Action", "OldData", "NewData", "ChangedBy", "ChangedAt")
        VALUES (TG_TABLE_NAME, CAST(NEW."ReportId" AS TEXT), 'UPDATE', to_jsonb(OLD), to_jsonb(NEW), current_user_id, now());
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO "AuditLogs" ("TableName", "RecordId", "Action", "OldData", "ChangedBy", "ChangedAt")
        VALUES (TG_TABLE_NAME, CAST(OLD."ReportId" AS TEXT), 'DELETE', to_jsonb(OLD), current_user_id, now());
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. Refined Audit Function for Users (Excludes Passwords - Phase 7.4)
CREATE OR REPLACE FUNCTION audit_users_trigger_func()
RETURNS TRIGGER AS $$
DECLARE
    current_user_id TEXT;
    old_data JSONB;
    new_data JSONB;
BEGIN
    BEGIN
        current_user_id := current_setting('app.current_user_id', true);
    EXCEPTION WHEN OTHERS THEN
        current_user_id := 'SYSTEM';
    END;

    IF current_user_id IS NULL OR current_user_id = '' THEN 
        current_user_id := 'SYSTEM'; 
    END IF;

    -- Phase 7.4: Filter out sensitive columns
    IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN
        new_data := to_jsonb(NEW) - 'PasswordHash' - 'SecurityStamp' - 'ConcurrencyStamp';
    END IF;
    
    IF (TG_OP = 'UPDATE' OR TG_OP = 'DELETE') THEN
        old_data := to_jsonb(OLD) - 'PasswordHash' - 'SecurityStamp' - 'ConcurrencyStamp';
    END IF;

    IF (TG_OP = 'INSERT') THEN
        INSERT INTO "AuditLogs" ("TableName", "RecordId", "Action", "NewData", "ChangedBy", "ChangedAt")
        VALUES (TG_TABLE_NAME, NEW."Id", 'INSERT', new_data, current_user_id, now());
    ELSIF (TG_OP = 'UPDATE') THEN
        -- Only log if actual data changed (ignoring password/stamp fields)
        IF (old_data = new_data) THEN RETURN NEW; END IF;
        
        INSERT INTO "AuditLogs" ("TableName", "RecordId", "Action", "OldData", "NewData", "ChangedBy", "ChangedAt")
        VALUES (TG_TABLE_NAME, NEW."Id", 'UPDATE', old_data, new_data, current_user_id, now());
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO "AuditLogs" ("TableName", "RecordId", "Action", "OldData", "ChangedBy", "ChangedAt")
        VALUES (TG_TABLE_NAME, OLD."Id", 'DELETE', old_data, current_user_id, now());
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260501105030_SecureAuditTriggers', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "AccomplishmentReportEXP" ADD "BreakDurationMinutes" integer NOT NULL DEFAULT 0;

ALTER TABLE "AccomplishmentReportEXP" ADD "BreakEndTime" time without time zone;

ALTER TABLE "AccomplishmentReportEXP" ADD "BreakStartTime" time without time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260501122814_AddBreakTrackingToAR', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "AccomplishmentReportEXP" ADD "IsModifiedByAdmin" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260503074720_AddIsModifiedByAdmin', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "ApprovalTeamId" integer;

ALTER TABLE "AspNetUsers" ADD "SubstituteId" text;

ALTER TABLE "AccomplishmentReportEXP" ADD "ApprovalFlowSnapshot" jsonb NOT NULL DEFAULT '{}';

ALTER TABLE "AccomplishmentReportEXP" ADD "CurrentApprovalStage" integer NOT NULL DEFAULT 0;

ALTER TABLE "AccomplishmentReportEXP" ADD "CurrentApproverId" text;

CREATE TABLE "ApprovalTeams" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Approvers" jsonb NOT NULL,
    CONSTRAINT "PK_ApprovalTeams" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260504084207_AddSequentialApproval', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE INDEX "IX_AspNetUsers_ApprovalTeamId" ON "AspNetUsers" ("ApprovalTeamId");

ALTER TABLE "AspNetUsers" ADD CONSTRAINT "FK_AspNetUsers_ApprovalTeams_ApprovalTeamId" FOREIGN KEY ("ApprovalTeamId") REFERENCES "ApprovalTeams" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260504085331_AddApprovalTeamAndSequentialFlow', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TABLE "Departments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Code" character varying(10) NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505054939_AddDepartmentTable', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "DepartmentId" integer;

ALTER TABLE "ApprovalTeams" ADD "DepartmentId" integer;

CREATE INDEX "IX_AspNetUsers_DepartmentId" ON "AspNetUsers" ("DepartmentId");

CREATE INDEX "IX_ApprovalTeams_DepartmentId" ON "ApprovalTeams" ("DepartmentId");

ALTER TABLE "ApprovalTeams" ADD CONSTRAINT "FK_ApprovalTeams_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id");

ALTER TABLE "AspNetUsers" ADD CONSTRAINT "FK_AspNetUsers_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505055054_LinkDepartmentToUserAndTeam', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" DROP CONSTRAINT "FK_AspNetUsers_ApprovalTeams_ApprovalTeamId";

ALTER TABLE "AspNetUsers" DROP CONSTRAINT "FK_AspNetUsers_Departments_DepartmentId";

ALTER TABLE "Departments" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Departments" ADD "CreatedBy" text;

ALTER TABLE "Departments" ADD "IsActive" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Departments" ADD "UpdatedAt" timestamp with time zone;

ALTER TABLE "Departments" ADD "UpdatedBy" text;

CREATE UNIQUE INDEX "IX_Departments_Code" ON "Departments" ("Code");

CREATE UNIQUE INDEX "IX_Departments_Name" ON "Departments" ("Name");

ALTER TABLE "AspNetUsers" ADD CONSTRAINT "FK_AspNetUsers_ApprovalTeams_ApprovalTeamId" FOREIGN KEY ("ApprovalTeamId") REFERENCES "ApprovalTeams" ("Id") ON DELETE SET NULL;

ALTER TABLE "AspNetUsers" ADD CONSTRAINT "FK_AspNetUsers_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505070626_AddDepartmentAuditFields', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Departments" ADD "IsSystem" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505073022_AddIsSystemToDepartment', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Departments" ALTER COLUMN "Name" TYPE character varying(20);

UPDATE "Departments" SET "IsActive" = true;

UPDATE "Departments" SET "Name" = 'Development' WHERE "Name" = 'Developement';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505074723_FixDepartmentDataAndSchema', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "ApprovalTeams" DROP COLUMN "Approvers";

CREATE TABLE "ApprovalTeamApprovers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ApprovalTeamId" integer NOT NULL,
    "UserId" text NOT NULL,
    "Order" integer NOT NULL,
    "AssignedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ApprovalTeamApprovers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ApprovalTeamApprovers_ApprovalTeams_ApprovalTeamId" FOREIGN KEY ("ApprovalTeamId") REFERENCES "ApprovalTeams" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ApprovalTeamApprovers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ApprovalTeamMembers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ApprovalTeamId" integer NOT NULL,
    "UserId" text NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ApprovalTeamMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ApprovalTeamMembers_ApprovalTeams_ApprovalTeamId" FOREIGN KEY ("ApprovalTeamId") REFERENCES "ApprovalTeams" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ApprovalTeamMembers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ApprovalTeamApprovers_ApprovalTeamId" ON "ApprovalTeamApprovers" ("ApprovalTeamId");

CREATE INDEX "IX_ApprovalTeamApprovers_UserId" ON "ApprovalTeamApprovers" ("UserId");

CREATE INDEX "IX_ApprovalTeamMembers_ApprovalTeamId" ON "ApprovalTeamMembers" ("ApprovalTeamId");

CREATE INDEX "IX_ApprovalTeamMembers_UserId" ON "ApprovalTeamMembers" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505130050_Phase18_RelationalApprovalTeams', '10.0.5');

COMMIT;

START TRANSACTION;
DROP INDEX "IX_ApprovalTeamMembers_UserId";

CREATE UNIQUE INDEX "IX_ApprovalTeamMembers_UserId" ON "ApprovalTeamMembers" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505144020_AddUniqueTeamMembershipConstraint', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "ApprovalTeamMembers" ALTER COLUMN "ApprovalTeamId" DROP NOT NULL;

ALTER TABLE "ApprovalTeamApprovers" ALTER COLUMN "ApprovalTeamId" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505161406_MakeApprovalTeamIdNullable', '10.0.5');

COMMIT;

START TRANSACTION;
DROP INDEX "IX_ApprovalTeamApprovers_UserId";

CREATE UNIQUE INDEX "IX_ApprovalTeamApprovers_UserId" ON "ApprovalTeamApprovers" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260506080129_AddUniqueApproverConstraint', '10.0.5');

COMMIT;

START TRANSACTION;
DROP INDEX "IX_ApprovalTeamApprovers_UserId";

CREATE UNIQUE INDEX "IX_ApprovalTeamApprovers_UserId_ApprovalTeamId" ON "ApprovalTeamApprovers" ("UserId", "ApprovalTeamId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260507053205_RelaxApproverConstraint', '10.0.5');

COMMIT;

